services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: API Gateway/Dockerfile
  addressstorecoverageservice:
    image: ${DOCKER_REGISTRY-}addressstorecoverageservice
    build:
      context: .
      dockerfile: Address & Store Coverage Service/Dockerfile
  cartservice:
    image: ${DOCKER_REGISTRY-}cartservice
    build:
      context: .
      dockerfile: Cart Service/Dockerfile
  catalogservice:
    image: ${DOCKER_REGISTRY-}catalogservice
    build:
      context: .
      dockerfile: Catalog Service/Dockerfile
  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: Identity service/Dockerfile
  orderfulfillmentservice:
    image: ${DOCKER_REGISTRY-}orderfulfillmentservice
    build:
      context: .
      dockerfile: Order & Fulfillment Service/Dockerfile
  paymentservice:
    image: ${DOCKER_REGISTRY-}paymentservice
    build:
      context: .
      dockerfile: Payment Service/Dockerfile
